---
name: CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        description: "Is a release"
        type: boolean
        default: false
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - "*.go"
      - "**/*.go"
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run golangci-lint
        run: hack/linter.sh

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run unit-tests
        run: hack/unit-tests.sh

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - unit-tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            arch: amd64
          - os: windows
            arch: arm64
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup golang
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 'stable'
          cache-dependency-path: go.sum

      - name: Build Artifact
        env:
          BUILD_RELEASE: ${{ inputs.release }}
        run: hack/fyne-cross.sh "${{ matrix.os }}" "${{ matrix.arch }}"

      - name: Get artifact file ending
        id: artifact-file-ending
        run: |
          if [ "${{ matrix.os }}" == "windows" ]; then
            echo "file-ending=zip" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.os }}" == "linux" ]; then
            echo "file-ending=tar.gz" >> $GITHUB_OUTPUT
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: "infraspace-savegame-editor_${{ matrix.os }}-${{ matrix.arch }}.${{ steps.artifact-file-ending.outputs.file-ending }}"
          path: "fyne-cross/dist/infraspace-savegame-editor_${{ matrix.os }}-${{ matrix.arch }}.${{ steps.artifact-file-ending.outputs.file-ending }}"
          retention-days: 1
          if-no-files-found: error
