---
name: CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        description: "Is a release"
        type: boolean
        default: false
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - "*.go"
      - "**/*.go"
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

jobs:
  lint:
    uses: heathcliff26/ci/.github/workflows/golang-fyne-lint.yaml@main

  unit-tests:
    uses: heathcliff26/ci/.github/workflows/golang-unit-tests.yaml@main
    with:
      cmd: hack/unit-tests.sh

  validate:
    uses: heathcliff26/ci/.github/workflows/golang-build.yaml@main
    with:
      cache: false
      cmd: "make validate"

  build:
    uses: heathcliff26/ci/.github/workflows/golang-fyne-build.yaml@main
    needs:
      - lint
      - unit-tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            arch: amd64
          - os: windows
            arch: arm64
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
    with:
      goos: "${{ matrix.os }}"
      goarch: "${{ matrix.arch }}"
      name: infraspace-savegame-editor
      release: ${{ inputs.release || false }}
