---
name: "Generate go test cover report"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "*.go"
      - "**/*.go"

jobs:
  generate-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1 # v1.10.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout main branch
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          token: "${{ steps.app-token.outputs.token }}"
          ref: "main"
          path: "main"

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 'stable'
          cache-dependency-path: go.sum

      - name: Generate reports
        run: |
          ${GITHUB_WORKSPACE}/main/hack/coverprofile.sh

      - name: Checkout gh-pages
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          token: "${{ steps.app-token.outputs.token }}"
          ref: "gh-pages"
          path: "gh-pages"

      - name: Copy files to gh-pages
        run: |
          set -e
          cp ${GITHUB_WORKSPACE}/main/coverprofiles/* ${GITHUB_WORKSPACE}/gh-pages/

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          commit_message: |
            Updated go coverprofiles

            Commit: ${{ github.sha }}
          commit_options: "--signoff"
          repository: "./gh-pages"
          commit_user_name: "bot-ahsoka[bot]"
          commit_user_email: "<bot-ahsoka[bot]@users.noreply.github.com>"
          commit_author: "bot-ahsoka[bot] <bot-ahsoka[bot]@users.noreply.github.com>"
          skip_dirty_check: false
          skip_fetch: true
          skip_checkout: true

