---
name: Release

on:
  workflow_dispatch:
    inputs:
      draft:
        description: "Create draft release"
        type: boolean
        default: true
      update:
        description: "Update existing release"
        type: boolean
        default: false
      version:
        description: "The version of the release"
        type: string
        required: true

jobs:
  build:
    uses: ./.github/workflows/ci.yaml

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Download artifacts
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4.1.0
        with:
          path: out
          merge-multiple: true

      - uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # v1.13.0
        with:
          allowUpdates: ${{ inputs.update }}
          artifacts: "out/infraspace-savegame-editor_*"
          artifactErrorsFailBuild: true
          draft: ${{ inputs.draft }}
          generateReleaseNotes: true
          tag: "${{ inputs.version }}"
