---
name: Release

on:
  workflow_dispatch:
    inputs:
      draft:
        description: "Create draft release"
        type: boolean
        default: true
      update:
        description: "Update existing release"
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/ci.yaml
    permissions:
      contents: read
    with:
      release: true

  release:
    uses: heathcliff26/ci/.github/workflows/golang-fyne-release.yaml@main
    needs: build
    permissions:
      contents: write
    with:
      draft: ${{ inputs.draft }}
      update: ${{ inputs.update }}
