---
name: Release

on:
  workflow_dispatch:
    inputs:
      draft:
        description: "Create draft release"
        type: boolean
        default: true
      update:
        description: "Update existing release"
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/ci.yaml
    with:
      release: true

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Extract Version
        id: version
        run: |
          set -ex
          version="$(cat FyneApp.toml | grep Version | grep -P -o "[0-9]+\.[0-9]+\.[0-9]+")"
          echo "version=v${version}" >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          path: dist
          merge-multiple: true

      - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          allowUpdates: ${{ inputs.update }}
          artifacts: "dist/*.tar.gz,dist/*.zip"
          artifactErrorsFailBuild: true
          draft: ${{ inputs.draft }}
          generateReleaseNotes: true
          tag: "${{ steps.version.outputs.version }}"
